server:
  port: '8085'
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/car-insurance-api
    username: root
    password: 12345

  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      jdbc.lob.non_contextual_creation: true
      ddl-auto: validate
      org.hibernate.envers.audit_table_suffix: _aud
  liquibase:
    drop-first: false
    change-log: classpath:/db/changelog/db.changelog-master.yml
